/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kullanici_bilgi_sistemi;

import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kursad
 */
public class kullanici extends javax.swing.JFrame {
    DefaultTableModel mymodel ;int r=1,c=0;//
    /**
     * Creates new form odev
     */
    public kullanici() {
        
        initComponents();
        mymodel= (DefaultTableModel) jTable1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        hkc98_jLabel1 = new javax.swing.JLabel();
        hkc98_jLabel2 = new javax.swing.JLabel();
        hkc98_jLabel3 = new javax.swing.JLabel();
        hkc98_jLabel4 = new javax.swing.JLabel();
        hkc98_jLabel5 = new javax.swing.JLabel();
        hkc98_jLabel6 = new javax.swing.JLabel();
        hkc98_jFormattedTextField1 = new javax.swing.JFormattedTextField();
        hkc98_jFormattedTextField2 = new javax.swing.JFormattedTextField();
        hkc98_jPasswordField1 = new javax.swing.JPasswordField();
        hkc98_jRadioButton1 = new javax.swing.JRadioButton();
        hkc98_jRadioButton2 = new javax.swing.JRadioButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        hkc98_jButton1 = new javax.swing.JButton();
        hkc98_jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("211213098");

        hkc98_jLabel1.setText("Yeni kullanıcı ekle");

        hkc98_jLabel2.setText("Kullanıcı adı");

        hkc98_jLabel3.setText("şifre");

        hkc98_jLabel4.setText("Doğum tarihi");

        hkc98_jLabel5.setText("cinsiyet");

        hkc98_jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hkc98_jLabel6.setText("İlerleme");

        hkc98_jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        hkc98_jFormattedTextField1.setToolTipText("");
        hkc98_jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hkc98_jFormattedTextField1ActionPerformed(evt);
            }
        });

        hkc98_jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        hkc98_jPasswordField1.setToolTipText("*");
        hkc98_jPasswordField1.setActionCommand("<Not Set>");
        hkc98_jPasswordField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        hkc98_jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hkc98_jPasswordField1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(hkc98_jRadioButton1);
        hkc98_jRadioButton1.setText("Kadın");

        buttonGroup1.add(hkc98_jRadioButton2);
        hkc98_jRadioButton2.setText("Erkek");

        jProgressBar1.setMaximum(5);

        hkc98_jButton1.setText("Tamamla");
        hkc98_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hkc98_jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(hkc98_jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(hkc98_jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hkc98_jRadioButton2))
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(hkc98_jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hkc98_jLabel2)
                            .addComponent(hkc98_jLabel6)
                            .addComponent(hkc98_jLabel5)
                            .addComponent(hkc98_jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hkc98_jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hkc98_jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hkc98_jPasswordField1)
                            .addComponent(hkc98_jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(hkc98_jLabel1)
                .addGap(18, 18, 18)
                .addComponent(hkc98_jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hkc98_jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(hkc98_jLabel3)
                .addGap(18, 18, 18)
                .addComponent(hkc98_jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(hkc98_jLabel4)
                .addGap(8, 8, 8)
                .addComponent(hkc98_jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hkc98_jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hkc98_jRadioButton1)
                    .addComponent(hkc98_jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(hkc98_jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(hkc98_jButton1))
        );

        hkc98_jLabel7.setText("Kayıtlı Kullanıcılar");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"211213098", "11.06.2001", "Erkek"},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kullanıcı adı", "Doğum tarihi", "Cinsiyet"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(hkc98_jLabel7)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(hkc98_jLabel7)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hkc98_jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hkc98_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hkc98_jFormattedTextField1ActionPerformed

    private void hkc98_jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hkc98_jPasswordField1ActionPerformed
        // TODO add your handling code here:
        hkc98_jPasswordField1.setEchoChar('*');
        
    }//GEN-LAST:event_hkc98_jPasswordField1ActionPerformed

    private void hkc98_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hkc98_jButton1ActionPerformed
        // TODO add your handling code here:      
        System.out.println(hkc98_jPasswordField1.getPassword());
        int i=0,control=1; 
        jProgressBar1.setValue(i);
        if(hkc98_jFormattedTextField1.getValue()!=""){
            System.out.println("kullanici ad girildi");
            i++;
            try {
                Thread.sleep(120);
            } catch (InterruptedException ex) {
                System.out.println("Hata : "+ ex.getMessage());
            }jProgressBar1.setValue(i);
        }
        else control--;
        
        if(hkc98_jPasswordField1.getPassword()!=null){
            System.out.println("sifre girildi");
            i++;
            try {
                Thread.sleep(120);
            } catch (InterruptedException ex) {
                System.out.println("Hata : "+ ex.getMessage());
            }jProgressBar1.setValue(i);
        }
        else control--;
        if(hkc98_jFormattedTextField2.getValue()!=""){
            System.out.println("dogum tarihi girildi");
            i++;
            try {
                Thread.sleep(120);
            } catch (InterruptedException ex) {
                System.out.println("Hata : "+ ex.getMessage());
            }jProgressBar1.setValue(i);
        }
        else control--;
        if(hkc98_jRadioButton1.isSelected()){
            System.out.println("cinsiyer secildi");
            i++;
            try {
                Thread.sleep(120);
            } catch (InterruptedException ex) {
                System.out.println("Hata : "+ ex.getMessage());
            }jProgressBar1.setValue(i);
        }
        else if(hkc98_jRadioButton2.isSelected()){
            System.out.println("cinsiyer secildi");
            i++;
            try {
                Thread.sleep(120);
            } catch (InterruptedException ex) {
                System.out.println("Hata : "+ ex.getMessage());
            }jProgressBar1.setValue(i);
        }
        else control--;
          
        if(control==1){
            int sifreint=Integer.parseInt(hkc98_jFormattedTextField1.getText())%1000;
            String sifre=Integer.toString(sifreint);
            String girilensifre = new String(hkc98_jPasswordField1.getPassword());
            
            if(girilensifre.equals(sifre)){
                i++;
                jProgressBar1.setValue(i);
                if(hkc98_jRadioButton1.isSelected()){
                    mymodel.setValueAt(hkc98_jFormattedTextField1.getValue(), r, c);c++;
                    mymodel.setValueAt(hkc98_jFormattedTextField2.getText() , r, c);c++;
                    mymodel.setValueAt(hkc98_jRadioButton1.getText()        , r, c);
                    
                    jTable1.setModel(mymodel);
                }

                if(hkc98_jRadioButton2.isSelected()){
                    mymodel.setValueAt(hkc98_jFormattedTextField1.getValue(), r, c);c++;
                    mymodel.setValueAt(hkc98_jFormattedTextField2.getText() , r, c);c++;
                    mymodel.setValueAt(hkc98_jRadioButton2.getText()        , r, c);
                    
                    jTable1.setModel(mymodel);
                }
                try {
                  Thread.sleep(120);
                } catch (InterruptedException ex) {
                   System.out.println("Hata : "+ ex.getMessage());
                }
                jProgressBar1.setValue(i);
                }
            
            else{
                System.out.println("Sifreyi Yanlis Girdiniz");
            }
        }
        else{
            System.out.println("eksik deger girdiniz");
        }
        
        System.out.println("komut bitti");
        i=0;
        System.out.println("r="+r+c);
        c=0;
        r++;
        System.out.println("r="+r+c);
        jProgressBar1.setValue(i);
    }//GEN-LAST:event_hkc98_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kullanici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kullanici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kullanici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kullanici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new kullanici().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton hkc98_jButton1;
    private javax.swing.JFormattedTextField hkc98_jFormattedTextField1;
    private javax.swing.JFormattedTextField hkc98_jFormattedTextField2;
    private javax.swing.JLabel hkc98_jLabel1;
    private javax.swing.JLabel hkc98_jLabel2;
    private javax.swing.JLabel hkc98_jLabel3;
    private javax.swing.JLabel hkc98_jLabel4;
    private javax.swing.JLabel hkc98_jLabel5;
    private javax.swing.JLabel hkc98_jLabel6;
    private javax.swing.JLabel hkc98_jLabel7;
    private javax.swing.JPasswordField hkc98_jPasswordField1;
    private javax.swing.JRadioButton hkc98_jRadioButton1;
    private javax.swing.JRadioButton hkc98_jRadioButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private String toString(int sifreint) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
